


PIPELINE/OUTPUT_FOLDER/GSE105318_DLD1_RANDOMMIDPOSSTRICT_40kb/TCGAcoad_msi_mss/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE105381_HepG2_RANDOMMIDPOSSTRICT_40kb/TCGAlihc_norm_lihc/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE105381_HepG2_RANDOMMIDPOSSTRICT_40kb/TCGAlihc_wt_mutCTNNB1/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE109229_BT474_RANDOMMIDPOSSTRICT_40kb/TCGAbrca_lum_bas/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE109229_SKBR3_RANDOMMIDPOSSTRICT_40kb/TCGAbrca_lum_bas/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE118514_22Rv1_RANDOMMIDPOSSTRICT_40kb/TCGAprad_norm_prad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE118514_RWPE1_RANDOMMIDPOSSTRICT_40kb/TCGAprad_norm_prad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/GSE99051_786_O_RANDOMMIDPOSSTRICT_40kb/TCGAkich_norm_kich/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/HMEC_RANDOMMIDPOSSTRICT_40kb/TCGAbrca_lum_bas/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG1_RANDOMMIDPOSSTRICT_40kb/TCGAluad_mutKRAS_mutEGFR/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG1_RANDOMMIDPOSSTRICT_40kb/TCGAluad_nonsmoker_smoker/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG1_RANDOMMIDPOSSTRICT_40kb/TCGAluad_norm_luad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG1_RANDOMMIDPOSSTRICT_40kb/TCGAluad_wt_mutKRAS/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG1_RANDOMMIDPOSSTRICT_40kb/TCGAlusc_norm_lusc/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAluad_mutKRAS_mutEGFR/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAluad_nonsmoker_smoker/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAluad_norm_luad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAluad_wt_mutKRAS/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LI_RANDOMMIDPOSSTRICT_40kb/TCGAlihc_norm_lihc/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LI_RANDOMMIDPOSSTRICT_40kb/TCGAlihc_wt_mutCTNNB1/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/Rao_HCT-116_2017_RANDOMMIDPOSSTRICT_40kb/TCGAcoad_msi_mss/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata





ENCSR312KHQ_SK-MEL-5_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
ENCSR444WCZ_A549_RANDOMMIDPOSSTRICT_40kb/TCGAluad_norm_luad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
ENCSR862OGI_RPMI-7951_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
LG2_RANDOMMIDPOSSTRICT_40kb/TCGAlusc_norm_lusc/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata



cp mnt/ptemp/marie/PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAlusc_norm_lusc/6pF_runPermutationsMeanLogFC/meanLogFC_permDT.Rdata /mnt/etemp/marie/v2_Yuanlong_Cancer_HiC_data_TAD_DA/PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSSTRICT_40kb/TCGAlusc_norm_lusc/6pF_runPermutationsMeanLogFC

cp mnt/ptemp/marie/PIPELINE/OUTPUT_FOLDER/ENCSR862OGI_RPMI-7951_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/6pF_runPermutationsMeanLogFC/meanLogFC_permDT.Rdata /mnt/etemp/marie/v2_Yuanlong_Cancer_HiC_data_TAD_DA/PIPELINE/OUTPUT_FOLDER/ENCSR862OGI_RPMI-7951_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/6pF_runPermutationsMeanLogFC


cp /mnt/pd4/marie/PIPELINE/OUTPUT_FOLDER/ENCSR312KHQ_SK-MEL-5_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/5pF_runPermutationsMedian/permutationsDT.Rdata /mnt/etemp/marie/v2_Yuanlong_Cancer_HiC_data_TAD_DA/PIPELINE/OUTPUT_FOLDER/ENCSR312KHQ_SK-MEL-5_RANDOMMIDPOSSTRICT_40kb/TCGAskcm_wt_mutCTNNB1/5pF_runPermutationsMedian





PIPELINE/OUTPUT_FOLDER/HMEC_RANDOMMIDPOSDISC_40kb/TCGAbrca_lum_bas/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata


PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSDISC_40kb/TCGAluad_mutKRAS_mutEGFR/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSDISC_40kb/TCGAluad_nonsmoker_smoker/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSDISC_40kb/TCGAluad_norm_luad/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LG2_RANDOMMIDPOSDISC_40kb/TCGAluad_wt_mutKRAS/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata

PIPELINE/OUTPUT_FOLDER/LI_RANDOMMIDPOSDISC_40kb/TCGAlihc_norm_lihc/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/LI_RANDOMMIDPOSDISC_40kb/TCGAlihc_wt_mutCTNNB1/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata
PIPELINE/OUTPUT_FOLDER/Rao_HCT-116_2017_RANDOMMIDPOSDISC_40kb/TCGAcoad_msi_mss/11sameNbrPF_runEmpPvalCombined/emp_pval_combined.Rdata

